CookLab/Web/CookLab.Web/Controllers/CategoriesController.cs
namespace CookLab.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using CookLab.Models.InputModels.Categories;
    using CookLab.Models.ViewModels.Categories;
    using CookLab.Services.Data;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;

    public class CategoriesController : BaseController
    {
        private readonly ICategoriesService categoriesService;
        private readonly IWebHostEnvironment webHostEnvironment;

        public CategoriesController(
            ICategoriesService categoriesService,
            IWebHostEnvironment webHostEnvironment)
        {
            this.categoriesService = categoriesService;
            this.webHostEnvironment = webHostEnvironment;
        }

        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CategoryInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            var rootPath = this.webHostEnvironment.WebRootPath;
            await this.categoriesService.CreateAsync(inputModel, rootPath);
            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> All(int id = 1)
        {
            int itemsPerPage = 12;
            var categories = await this.categoriesService.GetAllAsync<CategoryViewModel>();

            var viewModel = new CategoriesListViewModel
            {
                Categories = categories
                            .Skip((id - 1) * itemsPerPage)
                            .Take(itemsPerPage),
                CurrentPage = id,
                ItemsCount = categories.Count(),
                ItemsPerPage = itemsPerPage,
            };
            this.ViewData["Action"] = nameof(this.All);
            return this.View(viewModel);
        }
    }
}

CookLab/Web/CookLab.Web/Controllers/ContactsController.cs
namespace CookLab.Web.Controllers
{
    using System.Threading.Tasks;

    using CookLab.Common;
    using CookLab.Models.InputModels.ContactForms;
    using CookLab.Services.Data;

    using Microsoft.AspNetCore.Mvc;

    public class ContactsController : BaseController
    {
        private readonly IContactsService contactsService;

        public ContactsController(IContactsService contactsService)
        {
            this.contactsService = contactsService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            await this.contactsService.SendEmailToAdminAsync(inputModel);

            this.TempData[GlobalConstants.RedirectedFromContactForm] = true;
            return this.RedirectToAction(nameof(this.ThankYou));
        }

        public IActionResult ThankYou()
        {
            if (this.TempData[GlobalConstants.RedirectedFromContactForm] == null)
            {
                return this.NotFound();
            }

            return this.View();
        }
    }
}

CookLab/Web/CookLab.Web/Controllers/IngredientsController.cs
namespace CookLab.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CookLab.Models.InputModels.Ingredients;
    using CookLab.Models.ViewModels.Ingredients;
    using CookLab.Services.Data;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class IngredientsController : BaseController
    {
        private readonly IIngredientsService ingredientsService;

        public IngredientsController(IIngredientsService ingredientsService)
        {
            this.ingredientsService = ingredientsService;
        }

        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(IngredientInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            await this.ingredientsService.CreateAsync(inputModel);
            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> All(int id = 1)
        {
            var itemsPerPage = 15;
            var ingredients = await this.ingredientsService.GetAllAsync<IngredientViewModel>();

            var viewModel = new IngredientsListViewModel
            {
                Ingredients = ingredients
                            .Skip((id - 1) * itemsPerPage)
                            .Take(itemsPerPage),
                CurrentPage = id,
                ItemsCount = ingredients.Count(),
                ItemsPerPage = itemsPerPage,
            };
            this.ViewData["Action"] = nameof(this.All);
            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(string id)
        {
            var ingredient = await this.ingredientsService.GetByIdAsync<IngredientViewModel>(id);

            if (ingredient == null)
            {
                return this.NotFound();
            }

            return this.View(ingredient);
        }
    }
}

CookLab/Web/CookLab.Web/Controllers/RecipesController.cs
namespace CookLab.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using CookLab.Common;
    using CookLab.Data.Models;
    using CookLab.Models.InputModels.Recipes;
    using CookLab.Models.ViewModels.Categories;
    using CookLab.Models.ViewModels.Recipes;
    using CookLab.Services.Data;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class RecipesController : BaseController
    {
        private readonly IRecipesService recipesService;
        private readonly ICategoriesService categoriesService;
        private readonly IIngredientsService ingredientsService;
        private readonly ICookingVesselsService cookingVesselsService;
        private readonly ICategoryRecipesService categoryRecipeService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment webHostEnvironment;

        public RecipesController(
            IRecipesService recipesService,
            ICategoriesService categoriesService,
            IIngredientsService ingredientsService,
            ICookingVesselsService cookingVesselsService,
            ICategoryRecipesService categoryRecipeService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment webHostEnvironment)
        {
            this.recipesService = recipesService;
            this.categoriesService = categoriesService;
            this.ingredientsService = ingredientsService;
            this.cookingVesselsService = cookingVesselsService;
            this.categoryRecipeService = categoryRecipeService;
            this.userManager = userManager;
            this.webHostEnvironment = webHostEnvironment;
        }

        [Authorize]
        public async Task<IActionResult> Create()
        {
            var recipe = new RecipeInputModel
            {
                Categories = await this.categoriesService.GetAllCategoriesSelectListAsync(),
                Ingredients = await this.ingredientsService.GetAllIngredientsSelectListAsync(),
                CookingVessels = await this.cookingVesselsService.GetAllCookingVesselsSelectListAsync(),
            };

            return this.View(recipe);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(RecipeInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                inputModel.Categories = await this.categoriesService.GetAllCategoriesSelectListAsync();
                inputModel.Ingredients = await this.ingredientsService.GetAllIngredientsSelectListAsync();
                inputModel.CookingVessels = await this.cookingVesselsService.GetAllCookingVesselsSelectListAsync();

                return this.View(inputModel);
            }

            var rootPath = this.webHostEnvironment.WebRootPath;
            var userId = this.userManager.GetUserId(this.User);
            await this.recipesService.CreateAsync(userId, inputModel, rootPath);

            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> All(int id = 1)
        {
            int itemsPerPage = 9;
            var recipes = await this.recipesService.GetAllAsync<RecipeViewModel>();
            this.ViewData["Title"] = PageTitles.RecipeAllPageTitle;
            this.ViewData["Action"] = nameof(this.All);
            return this.View(this.CreateListViewModel(recipes, id, itemsPerPage));
        }

        public async Task<IActionResult> AllByCategory([FromQuery] int filterId, int id = 1)
        {
            int itemsPerPage = 9;
            var recipes = await this.recipesService.GetAllByCategoryAsync<RecipeViewModel>(filterId);
            var category = await this.categoriesService.GetByIdAsync<CategoryViewModel>(filterId);
            this.ViewData["Title"] = string.Format(PageTitles.RecipeAllByCategoryPageTitle, category.Name);
            this.ViewData["Action"] = nameof(this.AllByCategory);
            this.ViewData["FromQuery"] = filterId;
            return this.View(nameof(this.All), this.CreateListViewModel(recipes, id, itemsPerPage));
        }

        public async Task<IActionResult> AllCreatedBy([FromQuery] string filterId, int id = 1)
        {
            int itemsPerPage = 9;
            var recipes = await this.recipesService.GetAllByCreatorAsync<RecipeViewModel>(filterId);
            var user = await this.userManager.FindByIdAsync(filterId);
            this.ViewData["Title"] = string.Format(PageTitles.RecipeAllCreatedByPageTitle, user.UserName);
            this.ViewData["Action"] = nameof(this.AllCreatedBy);
            this.ViewData["FromQuery"] = filterId;
            return this.View(nameof(this.All), this.CreateListViewModel(recipes, id, itemsPerPage));
        }

        public async Task<IActionResult> AllCreatedByMe(int id = 1)
        {
            int itemsPerPage = 9;
            var userId = this.userManager.GetUserId(this.User);
            var recipes = await this.recipesService.GetAllByCreatorAsync<RecipeViewModel>(userId);
            var user = await this.userManager.FindByIdAsync(userId);
            this.ViewData["Title"] = string.Format(PageTitles.RecipeAllCreatedByPageTitle, user.UserName);
            this.ViewData["Action"] = nameof(this.AllCreatedByMe);
            return this.View(nameof(this.All), this.CreateListViewModel(recipes, id, itemsPerPage));
        }

        public async Task<IActionResult> AllMy(int id = 1)
        {
            int itemsPerPage = 9;
            var userId = this.userManager.GetUserId(this.User);
            var recipes = await this.recipesService.GetAllByUserAsync<RecipeViewModel>(userId);
            this.ViewData["Title"] = PageTitles.RecipeAllMyPageTitle;
            this.ViewData["Action"] = nameof(this.AllMy);
            return this.View(nameof(this.All), this.CreateListViewModel(recipes, id, itemsPerPage));
        }

        public async Task<IActionResult> Details(string id)
        {
            var recipe = await this.recipesService.GetByIdAsync<RecipeDetailsViewModel>(id);

            if (recipe == null)
            {
                return this.NotFound();
            }

            recipe.CookingVessels = await this.cookingVesselsService.GetAllCookingVesselsSelectListAsync();
            return this.View(recipe);
        }

        private RecipesListViewModel CreateListViewModel(IEnumerable<RecipeViewModel> recipes, int id, int itemsPerPage)
        {
            return new RecipesListViewModel
            {
                Recipes = recipes
                        .Skip((id - 1) * itemsPerPage)
                        .Take(itemsPerPage),
                CurrentPage = id,
                ItemsCount = recipes.Count(),
                ItemsPerPage = itemsPerPage,
            };
        }
    }
}

CookLab/Web/CookLab.Web/Views/Shared/HttpError.cshtml
@using CookLab.Models.ViewModels

@model HttpErrorViewModel
@{ this.ViewData["Title"] = PageTitles.HttpErrorPageTitle; }

<div class="container d-flex flex-column align-items-center mt-n5 mt-lg-0">
    <h1 class="text-wrap text-center pt-lg-3">@this.ViewData["Title"]: @Model.StatusCode</h1>
    <h3 class="text-wrap text-center">We are sorry for that!</h3>
    <div class="img-container-httpError rounded overflow-hidden my-3">
        <img src="~/assets/img/httpErrorImage.jpg" alt="Not found page" class="img-fluid img-httpError">
    </div>
    <div class="container d-flex flex-column align-items-center">
        <p class="text-center">
            We are sorry, the page you requested could not be found. Please go back to the homepage or use the contact form. Thank your for your understanding!
        </p>
        <div class="row justify-content-center align-items-center p-0">
            <a class="btn btn-primary m-3" asp-controller="Home" asp-action="Index">
                <span class="label label-primary">Home</span>
            </a>
            <a class="btn btn-primary m-3" asp-controller="Contacts" asp-action="Index">
                <span class="label label-primary">Contact</span>
            </a>
        </div>
    </div>
</div>

CookLab/Web/CookLab.Web/Views/Shared/_Layout.cshtml
@{
    this.Layout = "_LayoutMain";
}

<main role="main" class="main-masthead">
    @this.RenderBody()
</main>

@section Scripts{
    @await this.RenderSectionAsync("Scripts", required: false)
}

CookLab/Web/CookLab.Web/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta name="google-signin-client_id" content="75231322661-ajqsu3hsqb44ti0c49st70is1b8g77ua.apps.googleusercontent.com">
    <title>@this.ViewData["Title"]</title>
    <!-- Fontawesome-->
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <script defer src="~/lib/fontawesome/js/all.min.js" asp-append-version="true"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
    <!-- Third party plugin CSS-->
    <link href="~/lib/magnific-popup/dist/magnific-popup.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/select2/dist/css/select2.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/styles.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
</head>
<body id="page-top">
    <header>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Categories" asp-action="All">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Recipes" asp-action="All">Recipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="Ingredients" asp-action="All">Ingredients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" asp-area="" asp-controller="CookingVessels" asp-action="All">Cooking Vessels</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="masthead d-flex">
        <div class="container container-main-masthead my-auto">
            @this.RenderBody()
            <div class="fixed-bottom">
                <partial name="_CookieConsentPartial" />
            </div>
        </div>
    </div>

    <footer class="py-3 position-relative">
        <div class="container">
            <div class="small text-center text-white">
                &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a class="footer-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> - 
                <a class="footer-link" asp-area="" asp-controller="Contacts" asp-action="Index">Contact us</a>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-easing/dist/jquery.easing.1.3.umd.min.js" asp-append-version="true"></script>
    <script src="~/lib/magnific-popup/dist/jquery.magnific-popup.min.js" asp-append-version="true"></script>
    <script src="~/lib/popper.js/dist/umd/popper.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/lib/select2/dist/js/select2.min.js" asp-append-version="true"></script>
    <script src="~/js/scripts.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

CookLab/Web/CookLab.Web/Views/Shared/_LayoutWithSideBar.cshtml
@{
    this.Layout = "_LayoutMain";
    this.ViewData["RecipesCount"] = 5;
}

<div class="row">
    <main role="main" class="main-masthead col-md-7 col-lg-9">
        @this.RenderBody()
    </main>

    <aside class="col-md-5 col-lg-3 text-dark rounded my-md-5 sidebar bg-custom">
        <vc:latest-recipes count="@int.Parse(this.ViewData["RecipesCount"].ToString())"></vc:latest-recipes>
        <vc:most-popular-recipes count="@int.Parse(this.ViewData["RecipesCount"].ToString())"></vc:most-popular-recipes>
    </aside>
</div>

@section Scripts{
    @await this.RenderSectionAsync("Scripts", required: false)
}

CookLab/Web/CookLab.Web/Views/Shared/_NutritionPartial.cshtml
@using CookLab.Models.ViewModels.Nutritions

@model NutritionViewModel

<table class="table table-striped table-hover table-light col-md-6 mx-auto">
    <thead>
        <tr>
            <th scope="col">Nutrition per 100 Grams</th>
            <th scope="col">
                @if (Model.Ingredient != null)
                {
                    @Model.Ingredient.Name;
                }
                else
                {
                    @Model.Recipe.Name;
                }
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">Calories</th>
            <td>@Model.CaloriesToString</td>
        </tr>
        <tr>
            <th scope="row">Carbohydrates</th>
            <td>@Model.CarbohydratesToString</td>
        </tr>
        <tr>
            <th scope="row">Fats</th>
            <td>@Model.FatsToString</td>
        </tr>
        <tr>
            <th scope="row">Proteins</th>
            <td>@Model.ProteinsToString</td>
        </tr>
        <tr>
            <th scope="row">Fibres</th>
            <td>@Model.FibresToString</td>
        </tr>
    </tbody>
</table>

CookLab/Web/CookLab.Web/Views/Shared/_PaginationPartial.cshtml
@using CookLab.Models.ViewModels

@model PaginationViewModel

<div class="my-3">
    <ul class="pagination justify-content-center">
        @if (1 < Model.CurrentPage - 3)
        {
            <li class="page-item">
        <a class="page-link" asp-area="" asp-action="@this.ViewData["Action"]" asp-route-id="1" asp-route-filterId="@if (this.ViewData["FromQuery"]!=null){<text>@this.ViewData["FromQuery"]</text>}">1</a>
            </li>
        }
        <li class="page-item @if (!Model.HasPreviousPage) {<text>disabled</text>} ">
            <a class="page-link" asp-area="" asp-action="@this.ViewData["Action"]" asp-route-id="@Model.PreviousPage" asp-route-filterId="@if (this.ViewData["FromQuery"]!=null){<text>@this.ViewData["FromQuery"]</text>}">Prev</a>
        </li>
        @for (int i = Model.CurrentPage - 2; i < Model.CurrentPage; i++)
        {
            @if (i > 0)
            {
                <li class="page-item">
                    <a class="page-link" asp-area="" asp-action="@this.ViewData["Action"]" asp-route-id="@i" asp-route-filterId="@if (this.ViewData["FromQuery"]!=null){<text>@this.ViewData["FromQuery"]</text>}">@i</a>
                </li>
            }
        }
        <li class="page-item active" aria-current="page">
            <a class="page-link">@Model.CurrentPage <span class="sr-only">(current)</span></a>
        </li>
        @for (int i = Model.CurrentPage + 1; i < Model.CurrentPage + 3; i++)
        {
            @if (i <= Model.TotalPagesCount)
            {
                <li class="page-item">
                    <a class="page-link" asp-area="" asp-action="@this.ViewData["Action"]" asp-route-id="@i" asp-route-filterId="@if (this.ViewData["FromQuery"]!=null){<text>@this.ViewData["FromQuery"]</text>}">@i</a>
                </li>
            }
        }
        <li class="page-item @if (!Model.HasNextPage) {<text>disabled</text>}">
            <a class="page-link" asp-area="" asp-action="@this.ViewData["Action"]" asp-route-id="@Model.NextPage" asp-route-filterId="@if (this.ViewData["FromQuery"]!=null){<text>@this.ViewData["FromQuery"]</text>}">Next</a>
        </li>
        @if (Model.TotalPagesCount > Model.CurrentPage + 3)
        {
            <li class="page-item">
                <a class="page-link" asp-area="" asp-action="@this.ViewData["Action"]" asp-route-id="@Model.TotalPagesCount" asp-route-filterId="@if (this.ViewData["FromQuery"]!=null){<text>@this.ViewData["FromQuery"]</text>}">@Model.TotalPagesCount</a>
            </li>
        }
    </ul>
</div>