CookLab/Web/CookLab.Web/Areas/Administration/Controllers/CookingVesselsController.cs
namespace CookLab.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using CookLab.Models.ViewModels.CookingVessels;
    using CookLab.Services.Data;

    using Microsoft.AspNetCore.Mvc;

    public class CookingVesselsController : AdministrationController
    {
        private readonly ICookingVesselsService cookingVesselsService;

        public CookingVesselsController(ICookingVesselsService cookingVesselsService)
        {
            this.cookingVesselsService = cookingVesselsService;
        }

        public async Task<IActionResult> Delete(int id)
        {
            var cookingVessel = await this.cookingVesselsService.GetByIdAsync<CookingVesselDeleteViewModel>(id);

            if (cookingVessel == null)
            {
                return this.NotFound();
            }

            return this.View(cookingVessel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CookingVesselDeleteViewModel viewModel)
        {
            await this.cookingVesselsService.DeleteAsync(viewModel.Id);
            return this.RedirectToAction(nameof(Web.Controllers.CookingVesselsController.All), new { area = string.Empty });
        }
    }
}

CookLab/Web/CookLab.Web/Controllers/CookingVesselController.cs
namespace CookLab.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class CookingVesselController : BaseController
    {
        public IActionResult Create()
        {
            return this.View();
        }

        public IActionResult All()
        {
            return this.View();
        }
    }
}

CookLab/Web/CookLab.Web/Controllers/CookingVesselsController.cs
namespace CookLab.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using CookLab.Models.InputModels.CookingVessel;
    using CookLab.Models.ViewModels.CookingVessels;
    using CookLab.Services.Data;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    public class CookingVesselsController : BaseController
    {
        private readonly ICookingVesselsService cookingVesselsService;

        public CookingVesselsController(ICookingVesselsService cookingVesselsService)
        {
            this.cookingVesselsService = cookingVesselsService;
        }

        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Create(CookingVesselInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            var cookingVessel = await this.cookingVesselsService.CreateAsync(inputModel);

            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> All(int id = 1)
        {
            int itemsPerPage = 17;
            var cookingVessels = await this.cookingVesselsService.GetAllAsync<CookingVesselViewModel>();

            var viewModel = new CookingVesselsListViewModel
            {
                CookingVessels = cookingVessels
                                .Skip((id - 1) * itemsPerPage)
                                .Take(itemsPerPage),
                CurrentPage = id,
                ItemsCount = cookingVessels.Count(),
                ItemsPerPage = itemsPerPage,
            };
            this.ViewData["Action"] = nameof(this.All);
            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            var cookingVessel = await this.cookingVesselsService.GetByIdAsync<CookingVesselViewModel>(id);

            if (cookingVessel == null)
            {
                return this.NotFound();
            }

            return this.View(cookingVessel);
        }
    }
}

CookLab/Web/CookLab.Web/Areas/Administration/Views/CookingVessels/Delete.cshtml
@using CookLab.Models.ViewModels.CookingVessels

@model CookingVesselDeleteViewModel

@{
    this.ViewData["Title"] = string.Format(PageTitles.DeleteCookingVesselPageTitle, Model.Name);
}

<div class="row h-100 align-items-center justify-content-center text-center">
    <div class="col-lg-10 align-self-end">
        <h1 class="text-white font-weight-bold">@this.ViewData["Title"]</h1>
        <hr class="divider my-4" />
    </div>
    <div class="col-lg-8 align-self-baseline">
        <form asp-area="@GlobalConstants.AdministrationAreaName" asp-controller="CookingVessels" asp-action="Delete" method="post">
            <h4 class="text-danger bg-white-transparent rounded p-2 text-center font-weight-light mb-5">
                Are you sure you want to delete cooking vessel @Model.Name?
            </h4>
            <div class="row justify-content-md-center">
                <button type="submit" class="btn btn-danger col-md-3 m-3">Delete</button>
                <a class="btn btn-secondary col-md-3 m-3" asp-area="" asp-controller="CookingVessels" asp-action="Details" asp-route-id="@Model.Id">Back</a>
            </div>
        </form>
    </div>
</div>